MercDevs_ej2/Controllers/DatosfichatecnicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MercDevs_ej2.Models;

namespace MercDevs_ej2.Controllers
{
    public class DatosfichatecnicasController : Controller
    {
        private readonly MercyDeveloperContext _context;

        public DatosfichatecnicasController(MercyDeveloperContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> FichaTecnica(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fichaTecnica = await _context.Datosfichatecnicas
                .Where(d => d.IdDatosFichaTecnica == id)
                .Include(d => d.RecepcionEquipo)
                    .ThenInclude(d => d.IdClienteNavigation)
                .Include(d => d.Diagnosticosolucions)
                .ToListAsync();

            if (fichaTecnica == null || !fichaTecnica.Any())
            {
                return NotFound();
            }

            return View(fichaTecnica);
        }

        public async Task<IActionResult> Inicio()
        {
            var mercydevsEjercicio2Context = _context.Datosfichatecnicas.Include(d => d.RecepcionEquipo);
            return View(await mercydevsEjercicio2Context.ToListAsync());
        }

        // GET: Datosfichatecnicas
        public async Task<IActionResult> Index(int id)
        {
            var fichaTecnica = await _context.Datosfichatecnicas
                .Include(d => d.RecepcionEquipo)
                .Include(d => d.Diagnosticosolucions)
                .Include(d => d.RecepcionEquipo.IdClienteNavigation)
                .FirstOrDefaultAsync(d => d.RecepcionEquipoId == id);

            if (fichaTecnica == null)
            {
                return RedirectToAction("Create", new { id });
            }

            return View(fichaTecnica);
        }

        //Listar Datos ficha Tecnica por Recepción de Equipos de Cliente: VerDatosFichaTecnicaPorRecepcion

        public async Task<IActionResult> VerDatosFichaTecnicaPorRecepcion(int id)
        {
            var mercydevsEjercicio2Context = _context.Datosfichatecnicas
                .Where(d => d.RecepcionEquipoId == id)
                .Include(d => d.RecepcionEquipo);
            ViewData["IdRecepcionEquipo"] = id;
            return View(await mercydevsEjercicio2Context.ToListAsync());
        }


        // GET: Datosfichatecnicas/Diagnosticosolucionpordatosficha/5
        public async Task<IActionResult> Diagnosticosolucionpordatosficha(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verdiagnostico = await _context.Datosfichatecnicas
                .Include(r => r.Diagnosticosolucions)
                .Include(r => r.RecepcionEquipo)
                .Include(d => d.RecepcionEquipo.IdClienteNavigation)
                .FirstOrDefaultAsync(m => m.IdDatosFichaTecnica == id);
            if (verdiagnostico == null)
            {
                return NotFound();
            }

            return View(verdiagnostico);
        }

        // GET: Datosfichatecnicas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosfichatecnica = await _context.Datosfichatecnicas
                .Include(d => d.RecepcionEquipo)
                .FirstOrDefaultAsync(m => m.IdDatosFichaTecnica == id);
            if (datosfichatecnica == null)
            {
                return NotFound();
            }

            return View(datosfichatecnica);
        }

        // GET: Datosfichatecnicas/Create
        public IActionResult Create(int? id)
        {
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id");
            ViewData["IdRecepcionEquipo"] = id;
            return View();
        }

        // POST: Datosfichatecnicas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id,[Bind("IdDatosFichaTecnica,FechaInicio,FechaFinalizacion,PobservacionesRecomendaciones,Soinstalado,SuiteOfficeInstalada,LectorPdfinstalado,NavegadorWebInstalado,AntivirusInstalado,RecepcionEquipoId")] Datosfichatecnica datosfichatecnica)
        {
            if (datosfichatecnica.FechaInicio != null)
            {
                datosfichatecnica.RecepcionEquipoId = Convert.ToInt32(id);
                _context.Add(datosfichatecnica);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Recepcionequipoes");
            }
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id", datosfichatecnica.RecepcionEquipoId);
            return View(datosfichatecnica);
        }

        // GET: Datosfichatecnicas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosfichatecnica = await _context.Datosfichatecnicas.FindAsync(id);
            if (datosfichatecnica == null)
            {
                return NotFound();
            }
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id", datosfichatecnica.RecepcionEquipoId);
            return View(datosfichatecnica);
        }

        // POST: Datosfichatecnicas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDatosFichaTecnica,FechaInicio,FechaFinalizacion,PobservacionesRecomendaciones,Soinstalado,SuiteOfficeInstalada,LectorPdfinstalado,NavegadorWebInstalado,AntivirusInstalado,RecepcionEquipoId")] Datosfichatecnica datosfichatecnica)
        {
            if (id != datosfichatecnica.IdDatosFichaTecnica)
            {
                return NotFound();
            }

            if (datosfichatecnica.FechaInicio != null)
            {
                try
                {
                    _context.Update(datosfichatecnica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DatosfichatecnicaExists(datosfichatecnica.IdDatosFichaTecnica))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Inicio));
            }
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id", datosfichatecnica.RecepcionEquipoId);
            return View(datosfichatecnica);
        }

        // GET: Datosfichatecnicas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosfichatecnica = await _context.Datosfichatecnicas
                .Include(d => d.RecepcionEquipo)
                .FirstOrDefaultAsync(m => m.IdDatosFichaTecnica == id);
            if (datosfichatecnica == null)
            {
                return NotFound();
            }

            return View(datosfichatecnica);
        }

        // POST: Datosfichatecnicas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var datosfichatecnica = await _context.Datosfichatecnicas.FindAsync(id);
            if (datosfichatecnica != null)
            {
                _context.Datosfichatecnicas.Remove(datosfichatecnica);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DatosfichatecnicaExists(int id)
        {
            return _context.Datosfichatecnicas.Any(e => e.IdDatosFichaTecnica == id);
        }
    }
}

MercDevs_ej2/Views/Recepcionequipoes/Create.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Recepcion de Equipo</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"> Id del Cliente</label>
                <select asp-for="IdCliente" class ="form-control" asp-items="ViewBag.IdCliente"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdServicio" class="control-label"> Id del Servicio</label>
                <select asp-for="IdServicio" class ="form-control" asp-items="ViewBag.IdServicio"></select>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoPc" class="control-label">Ingrese el tipo de pc</label>
                <input asp-for="TipoPc" class="form-control" />
                <span asp-validation-for="TipoPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accesorio" class="control-label">Accesorios</label>
                <input asp-for="Accesorio" class="form-control" />
                <span asp-validation-for="Accesorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaPc" class="control-label">marca del Pc</label>
                <input asp-for="MarcaPc" class="form-control" />
                <span asp-validation-for="MarcaPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeloPc" class="control-label">el Modelo del pc</label>
                <input asp-for="ModeloPc" class="form-control" />
                <span asp-validation-for="ModeloPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nserie" class="control-label"> N° Serie del Pc</label>
                <input asp-for="Nserie" class="form-control" />
                <span asp-validation-for="Nserie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadRam" class="control-label">Capacidad de Ram</label>
                <input asp-for="CapacidadRam" class="form-control" />
                <span asp-validation-for="CapacidadRam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoAlmacenamiento" class="control-label">Tipo de almacenamieto</label>
                <input asp-for="TipoAlmacenamiento" class="form-control" />
                <span asp-validation-for="TipoAlmacenamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadAlmacenamiento" class="control-label">Capacidad de Almacenamiento</label>
                <input asp-for="CapacidadAlmacenamiento" class="form-control" />
                <span asp-validation-for="CapacidadAlmacenamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoGpu" class="control-label">Tipo de Gpu</label>
                <input asp-for="TipoGpu" class="form-control" />
                <span asp-validation-for="TipoGpu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grafico" class="control-label">Graficos</label>
                <input asp-for="Grafico" class="form-control" />
                <span asp-validation-for="Grafico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label">Estado</label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="crear Recepcion" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><button class="btn btn-secondary">Volver a la lista</button></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MercDevs_ej2/Views/Recepcionequipoes/Delete.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar Recepcion de equipo</h1>

<h3>¿estas seguro de que quieres eliminar esto?</h3>
<div>

    <hr />
    <dl class="row ">
        <dt class="col-sm-2">
            Fecha:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <hr style="background-color:black" />
        <dt class="col-sm-2">
            Tipo de PC
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoPc)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            AccesoriosS
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Accesorio)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Marca de Pc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MarcaPc)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            modelo de Pc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModeloPc)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            N° Serie
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nserie)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Capacidad de Ram
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapacidadRam)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Tipo almacenamiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Cap Almacenamiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapacidadAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Tipo Gpu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoGpu)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Graficos
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grafico)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            Id cliente
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation.IdCliente)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Id servicio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.IdServicio)
        </dd>
        <hr style="background-color:black" />


    </dl>
</div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> 
        <a asp-action="Index"><button class="btn btn-secondary">volver a la lista</button></a>
    </form>
</div>

MercDevs_ej2/Views/Recepcionequipoes/Details.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de recepcion</h1>

<div>

    <hr />
    <dl class="row ">
        <dt class = "col-sm-2">
            Fecha:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <hr style="background-color:black"/>
        <dt class = "col-sm-2">
            Tipo de PC
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoPc)
        </dd>
        <hr style="background-color:black" />

        <dt class = "col-sm-2">
           AccesoriosS
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Accesorio)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Marca de Pc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarcaPc)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            modelo de Pc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeloPc)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            N° Serie
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nserie)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Capacidad de Ram
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacidadRam)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Tipo almacenamiento
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Cap Almacenamiento
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacidadAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Tipo Gpu
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoGpu)
        </dd>
        <hr style="background-color:black" />


        <dt class = "col-sm-2">
            Graficos
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grafico)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <hr style="background-color:black" />

        <dt class = "col-sm-2">
            Id cliente
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation.IdCliente)
        </dd>
        <hr style="background-color:black"/>


        <dt class = "col-sm-2">
            Id servicio
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.IdServicio)
        </dd>
        <hr style="background-color:black" />


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id"><button class="btn btn-warning">editar</button></a>
    <a asp-action="Index"><button class="btn btn-secondary">volver a listado</button></a>
    <form method="post" asp-action="Finalizar" asp-route-id="@Model?.Id">
        <button type="submit" class="btn btn-info">Finalizar Recepción</button>
    </form>
</div>

MercDevs_ej2/Views/Recepcionequipoes/DetailsId.cshtml
@model MercDevs_ej2.Models.Recepcionequipo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de recepcion</h1>

<div>

    <hr />
    <dl class="row ">
        <dt class="col-sm-2">
            Nombre Servicio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.Nombre)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            Sku
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.Sku)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            Fecha:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <hr style="background-color:black" />
        <dt class="col-sm-2">
            Tipo de PC
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoPc)
        </dd>
        <hr style="background-color:black" />

        <dt class="col-sm-2">
            AccesoriosS
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Accesorio)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Marca de Pc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MarcaPc)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            modelo de Pc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModeloPc)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            N° Serie
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nserie)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Capacidad de Ram
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapacidadRam)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Tipo almacenamiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Cap Almacenamiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapacidadAlmacenamiento)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Tipo Gpu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoGpu)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Graficos
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grafico)
        </dd>
        <hr style="background-color:black" />


        <dt class="col-sm-2">
            Id cliente
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation.IdCliente)
        </dd>
        <hr style="background-color:black" />


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id"><button class="btn btn-warning">editar</button></a>
    <a asp-action="Index"><button class="btn btn-secondary">volver a listado</button></a>
    <form method="post" asp-action="Finalizar" asp-route-id="@Model?.Id">
        <button type="submit" class="btn btn-info">Finalizar Recepción</button>
    </form>
</div>

MercDevs_ej2/Views/Recepcionequipoes/Index.cshtml
@model IEnumerable<MercDevs_ej2.Models.Recepcionequipo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index Recepcion De equipos</h1>
<body style="align-content:center">
<p>
        <a asp-action="Create"><button type="button" class="btn btn-success ">Crear Recepcion</button></a>
</p>
<table class="table">
    <thead td style="white-space: nowrap;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoPc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MarcaPc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModeloPc)
            </th>
            <th>
               Id Cliente
            </th>
            <th>
                Id servicio    
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody style="text-align">
@foreach (var item in Model) {
        <tr>
            <td style="white-space: nowrap;">
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td style="white-space: nowrap;">
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoPc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarcaPc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModeloPc)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Grafico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdClienteNavigation.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdServicioNavigation.Nombre)
            </td>
            <td>

                <div class="d-flex justify-content-around" >
                    <button class="btn btn-info">
                    @Html.ActionLink("Ficha Técnica", "Index", "Datosfichatecnicas", new { id = item.Id }, null)
                    </button>
                    <a asp-action="Edit" asp-route-id="@item.Id">
                        <button type="button" class="btn btn-primary" style="width:100%">Editar</button></a>

                    <a asp-action="Details" asp-route-id="@item.Id">
                        <button type="button" class="btn btn-info" style="width:100%">Detalles</button></a> 

                    <a asp-action="Delete" asp-route-id="@item.Id">
                            <button type="button" class="btn btn-danger" style="width:100%">Borrar</button>
                    </a>
                            <form method="post" asp-action="Finalizar" asp-route-id="@item?.Id">
                                <button type="submit" class="btn btn-warning">Finalizar Recepción</button>
                            </form>
                    </div>
            </td>
        </tr>
}
    </tbody>
</table>
</body>

MercDevs_ej2/Views/Recepcionequipoes/IndexId.cshtml
@model IEnumerable<MercDevs_ej2.Models.Recepcionequipo>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista Recepcion De equipos</h1>
<body style="align-content:center">
    <p>
        <a asp-action="Create"><button type="button" class="btn btn-success ">Crear Recepcion</button></a>
    </p>
    <table class="table">
        <thead td style="white-space: nowrap;">
            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.Fecha)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoPc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MarcaPc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModeloPc)
                </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody style="text-align">
            @foreach (var item in Model)
            {
                <tr>
                    <td style="white-space: nowrap;">
                        @Html.DisplayFor(modelItem => item.Fecha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoPc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MarcaPc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModeloPc)
                    </td>
                    
                    <td>

                        <div class="d-flex justify-content-around" style="gap:10px">
                            <a asp-action="Edit" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-primary" style="width:100%">Editar</button>
                            </a>

                            <a asp-action="DetailsId" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-info" style="width:100%">Detalle</button>
                            </a>

                            <a asp-action="Delete" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-danger" style="width:100%">Borrar</button>
                            </a>

                            <a asp-controller="Datosfichatecnicas" asp-action="VerDatosFichaTecnicaPorRecepcion" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-info" style="width:100%">Datos Ficha</button>
                            </a>

                            <form method="post" asp-action="Finalizar" asp-route-id="@item?.Id">
                                <button type="submit" class="btn btn-warning">Finalizar Recepción</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>