MercDevs_ej2/Models/Datosfichatecnica.cs
using System;
using System.Collections.Generic;

namespace MercDevs_ej2.Models;

public partial class Datosfichatecnica
{
    public int IdDatosFichaTecnica { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFinalizacion { get; set; }

    /// <summary>
    /// Por el Tecnico
    /// </summary>
    public string? PobservacionesRecomendaciones { get; set; }

    /// <summary>
    /// 0:Windows 10 ; 1: Windows 11; 2: Linux
    /// </summary>
    public int? Soinstalado { get; set; }

    /// <summary>
    /// 0: Microsoft Office 2013 ; 1: Microsoft Office 2019 ; 2: Microsoft Office 365 ; 3: OpenOffice
    /// </summary>
    public int? SuiteOfficeInstalada { get; set; }

    /// <summary>
    /// 0:No Instalado ; 1: Instalado 2: No aplica
    /// </summary>
    public int? LectorPdfinstalado { get; set; }

    /// <summary>
    /// 0:No instalado ; 1: Chrome ; 2: Firefox; 3: Chrome y Firefox
    /// </summary>
    public int? NavegadorWebInstalado { get; set; }

    public string? AntivirusInstalado { get; set; }

    public int RecepcionEquipoId { get; set; }

    public virtual ICollection<Diagnosticosolucion> Diagnosticosolucions { get; set; } = new List<Diagnosticosolucion>();

    public virtual Recepcionequipo RecepcionEquipo { get; set; } = null!;
}

MercDevs_ej2/Controllers/DatosfichatecnicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MercDevs_ej2.Models;

namespace MercDevs_ej2.Controllers
{
    public class DatosfichatecnicasController : Controller
    {
        private readonly MercyDeveloperContext _context;

        public DatosfichatecnicasController(MercyDeveloperContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> FichaTecnica(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fichaTecnica = await _context.Datosfichatecnicas
                .Where(d => d.IdDatosFichaTecnica == id)
                .Include(d => d.RecepcionEquipo)
                    .ThenInclude(d => d.IdClienteNavigation)
                .Include(d => d.Diagnosticosolucions)
                .ToListAsync();

            if (fichaTecnica == null || !fichaTecnica.Any())
            {
                return NotFound();
            }

            return View(fichaTecnica);
        }

        public async Task<IActionResult> Inicio()
        {
            var mercydevsEjercicio2Context = _context.Datosfichatecnicas.Include(d => d.RecepcionEquipo);
            return View(await mercydevsEjercicio2Context.ToListAsync());
        }

        // GET: Datosfichatecnicas
        public async Task<IActionResult> Index(int id)
        {
            var fichaTecnica = await _context.Datosfichatecnicas
                .Include(d => d.RecepcionEquipo)
                .Include(d => d.Diagnosticosolucions)
                .Include(d => d.RecepcionEquipo.IdClienteNavigation)
                .FirstOrDefaultAsync(d => d.RecepcionEquipoId == id);

            if (fichaTecnica == null)
            {
                return RedirectToAction("Create", new { id });
            }

            return View(fichaTecnica);
        }

        //Listar Datos ficha Tecnica por Recepción de Equipos de Cliente: VerDatosFichaTecnicaPorRecepcion

        public async Task<IActionResult> VerDatosFichaTecnicaPorRecepcion(int id)
        {
            var mercydevsEjercicio2Context = _context.Datosfichatecnicas
                .Where(d => d.RecepcionEquipoId == id)
                .Include(d => d.RecepcionEquipo);
            ViewData["IdRecepcionEquipo"] = id;
            return View(await mercydevsEjercicio2Context.ToListAsync());
        }


        // GET: Datosfichatecnicas/Diagnosticosolucionpordatosficha/5
        public async Task<IActionResult> Diagnosticosolucionpordatosficha(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verdiagnostico = await _context.Datosfichatecnicas
                .Include(r => r.Diagnosticosolucions)
                .Include(r => r.RecepcionEquipo)
                .Include(d => d.RecepcionEquipo.IdClienteNavigation)
                .FirstOrDefaultAsync(m => m.IdDatosFichaTecnica == id);
            if (verdiagnostico == null)
            {
                return NotFound();
            }

            return View(verdiagnostico);
        }

        // GET: Datosfichatecnicas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosfichatecnica = await _context.Datosfichatecnicas
                .Include(d => d.RecepcionEquipo)
                .FirstOrDefaultAsync(m => m.IdDatosFichaTecnica == id);
            if (datosfichatecnica == null)
            {
                return NotFound();
            }

            return View(datosfichatecnica);
        }

        // GET: Datosfichatecnicas/Create
        public IActionResult Create(int? id)
        {
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id");
            ViewData["IdRecepcionEquipo"] = id;
            return View();
        }

        // POST: Datosfichatecnicas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id,[Bind("IdDatosFichaTecnica,FechaInicio,FechaFinalizacion,PobservacionesRecomendaciones,Soinstalado,SuiteOfficeInstalada,LectorPdfinstalado,NavegadorWebInstalado,AntivirusInstalado,RecepcionEquipoId")] Datosfichatecnica datosfichatecnica)
        {
            if (datosfichatecnica.FechaInicio != null)
            {
                datosfichatecnica.RecepcionEquipoId = Convert.ToInt32(id);
                _context.Add(datosfichatecnica);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Recepcionequipoes");
            }
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id", datosfichatecnica.RecepcionEquipoId);
            return View(datosfichatecnica);
        }

        // GET: Datosfichatecnicas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosfichatecnica = await _context.Datosfichatecnicas.FindAsync(id);
            if (datosfichatecnica == null)
            {
                return NotFound();
            }
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id", datosfichatecnica.RecepcionEquipoId);
            return View(datosfichatecnica);
        }

        // POST: Datosfichatecnicas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDatosFichaTecnica,FechaInicio,FechaFinalizacion,PobservacionesRecomendaciones,Soinstalado,SuiteOfficeInstalada,LectorPdfinstalado,NavegadorWebInstalado,AntivirusInstalado,RecepcionEquipoId")] Datosfichatecnica datosfichatecnica)
        {
            if (id != datosfichatecnica.IdDatosFichaTecnica)
            {
                return NotFound();
            }

            if (datosfichatecnica.FechaInicio != null)
            {
                try
                {
                    _context.Update(datosfichatecnica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DatosfichatecnicaExists(datosfichatecnica.IdDatosFichaTecnica))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Inicio));
            }
            ViewData["RecepcionEquipoId"] = new SelectList(_context.Recepcionequipos, "Id", "Id", datosfichatecnica.RecepcionEquipoId);
            return View(datosfichatecnica);
        }

        // GET: Datosfichatecnicas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosfichatecnica = await _context.Datosfichatecnicas
                .Include(d => d.RecepcionEquipo)
                .FirstOrDefaultAsync(m => m.IdDatosFichaTecnica == id);
            if (datosfichatecnica == null)
            {
                return NotFound();
            }

            return View(datosfichatecnica);
        }

        // POST: Datosfichatecnicas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var datosfichatecnica = await _context.Datosfichatecnicas.FindAsync(id);
            if (datosfichatecnica != null)
            {
                _context.Datosfichatecnicas.Remove(datosfichatecnica);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DatosfichatecnicaExists(int id)
        {
            return _context.Datosfichatecnicas.Any(e => e.IdDatosFichaTecnica == id);
        }
    }
}

MercDevs_ej2/Controllers/DiagnosticosolucionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MercDevs_ej2.Models;

namespace MercDevs_ej2.Controllers
{
    public class DiagnosticosolucionsController : Controller
    {
        private readonly MercyDeveloperContext _context;

        public DiagnosticosolucionsController(MercyDeveloperContext context)
        {
            _context = context;
        }

        // GET: Diagnosticosolucions
        public async Task<IActionResult> Index()
        {
            var mercyDeveloperContext = _context.Diagnosticosolucions.Include(d => d.DatosFichaTecnica);
            return View(await mercyDeveloperContext.ToListAsync());
        }

        // GET: Diagnosticosolucions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diagnosticosolucion = await _context.Diagnosticosolucions
                .Include(d => d.DatosFichaTecnica)
                .FirstOrDefaultAsync(m => m.IdDiagnosticoSolucion == id);
            if (diagnosticosolucion == null)
            {
                return NotFound();
            }

            return View(diagnosticosolucion);
        }

        // GET: Diagnosticosolucions/Create
        public IActionResult Create()
        {
            ViewData["DatosFichaTecnicaId"] = new SelectList(_context.Datosfichatecnicas, "IdDatosFichaTecnica", "IdDatosFichaTecnica");
            return View();
        }

        // POST: Diagnosticosolucions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDiagnosticoSolucion,DescripcionDiagnostico,DescripcionSolucion,DatosFichaTecnicaId")] Diagnosticosolucion diagnosticosolucion)
        {
            if (diagnosticosolucion.DescripcionSolucion != null)
            {
                _context.Add(diagnosticosolucion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DatosFichaTecnicaId"] = new SelectList(_context.Datosfichatecnicas, "IdDatosFichaTecnica", "IdDatosFichaTecnica", diagnosticosolucion.DatosFichaTecnicaId);
            return View(diagnosticosolucion);
        }

        // GET: Diagnosticosolucions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diagnosticosolucion = await _context.Diagnosticosolucions.FindAsync(id);
            if (diagnosticosolucion == null)
            {
                return NotFound();
            }
            ViewData["DatosFichaTecnicaId"] = new SelectList(_context.Datosfichatecnicas, "IdDatosFichaTecnica", "IdDatosFichaTecnica", diagnosticosolucion.DatosFichaTecnicaId);
            return View(diagnosticosolucion);
        }

        // POST: Diagnosticosolucions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDiagnosticoSolucion,DescripcionDiagnostico,DescripcionSolucion,DatosFichaTecnicaId")] Diagnosticosolucion diagnosticosolucion)
        {
            if (id != diagnosticosolucion.IdDiagnosticoSolucion)
            {
                return NotFound();
            }

            if (diagnosticosolucion.DescripcionSolucion != null)
            {
                try
                {
                    _context.Update(diagnosticosolucion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiagnosticosolucionExists(diagnosticosolucion.IdDiagnosticoSolucion))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DatosFichaTecnicaId"] = new SelectList(_context.Datosfichatecnicas, "IdDatosFichaTecnica", "IdDatosFichaTecnica", diagnosticosolucion.DatosFichaTecnicaId);
            return View(diagnosticosolucion);
        }

        // GET: Diagnosticosolucions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diagnosticosolucion = await _context.Diagnosticosolucions
                .Include(d => d.DatosFichaTecnica)
                .FirstOrDefaultAsync(m => m.IdDiagnosticoSolucion == id);
            if (diagnosticosolucion == null)
            {
                return NotFound();
            }

            return View(diagnosticosolucion);
        }

        // POST: Diagnosticosolucions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var diagnosticosolucion = await _context.Diagnosticosolucions.FindAsync(id);
            if (diagnosticosolucion != null)
            {
                _context.Diagnosticosolucions.Remove(diagnosticosolucion);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DiagnosticosolucionExists(int id)
        {
            return _context.Diagnosticosolucions.Any(e => e.IdDiagnosticoSolucion == id);
        }
    }
}

MercDevs_ej2/Views/Datosfichatecnicas/Create.cshtml
@model MercDevs_ej2.Models.Datosfichatecnica

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Datos ficha tecnica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        <form asp-action="Create" asp-route-id="@ViewData["IdRecepcionEquipo"]">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinalizacion" class="control-label"></label>
                <input asp-for="FechaFinalizacion" class="form-control" />
                <span asp-validation-for="FechaFinalizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PobservacionesRecomendaciones" class="control-label"></label>
                <input asp-for="PobservacionesRecomendaciones" class="form-control" />
                <span asp-validation-for="PobservacionesRecomendaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soinstalado" class="control-label"></label>
                <input asp-for="Soinstalado" class="form-control" />
                <span asp-validation-for="Soinstalado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuiteOfficeInstalada" class="control-label"></label>
                <input asp-for="SuiteOfficeInstalada" class="form-control" />
                <span asp-validation-for="SuiteOfficeInstalada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LectorPdfinstalado" class="control-label"></label>
                <input asp-for="LectorPdfinstalado" class="form-control" />
                <span asp-validation-for="LectorPdfinstalado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NavegadorWebInstalado" class="control-label"></label>
                <input asp-for="NavegadorWebInstalado" class="form-control" />
                <span asp-validation-for="NavegadorWebInstalado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AntivirusInstalado" class="control-label"></label>
                <input asp-for="AntivirusInstalado" class="form-control" />
                <span asp-validation-for="AntivirusInstalado" class="text-danger"></span>
            </div>
            <!--
            <div class="form-group">
                <label asp-for="RecepcionEquipoId" class="control-label"></label>
                <select asp-for="RecepcionEquipoId" class ="form-control" asp-items="ViewBag.RecepcionEquipoId"></select>
            </div>
            -->
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button class="btn btn-secondary" onclick="window.history.back();">Volver a la lista</button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MercDevs_ej2/Views/Datosfichatecnicas/Delete.cshtml
@model MercDevs_ej2.Models.Datosfichatecnica

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>Estas seguro de borrar esto?</h3>
<div>
    <h4>Datos ficha tecnica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFinalizacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFinalizacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PobservacionesRecomendaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PobservacionesRecomendaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Soinstalado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Soinstalado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuiteOfficeInstalada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuiteOfficeInstalada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LectorPdfinstalado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LectorPdfinstalado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NavegadorWebInstalado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NavegadorWebInstalado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AntivirusInstalado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AntivirusInstalado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecepcionEquipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecepcionEquipo.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdDatosFichaTecnica" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <button class="btn btn-secondary" onclick="window.history.back();">Volver a la lista</button>
    </form>
</div>

MercDevs_ej2/Views/Datosfichatecnicas/Diagnosticosolucionpordatosficha.cshtml
@model MercDevs_ej2.Models.Datosfichatecnica

<h2>Datos de la Ficha Tecnica</h2>
<div>
    <p>ID Ficha: @Model.IdDatosFichaTecnica</p>
    <p>ID Recepcion: @Model.RecepcionEquipo.Id</p>
    <p>Fecha Inicio: @Model.FechaInicio</p>
    <p>Fecha Finalización: @Model.FechaFinalizacion</p>
    <p>Nombre: @Model.RecepcionEquipo.IdClienteNavigation.Nombre</p>
    <p>Apellido: @Model.RecepcionEquipo.IdClienteNavigation.Apellido</p>
    <p>Celular: @Model.RecepcionEquipo.IdClienteNavigation.Telefono</p>
    <p>Celular: @Model.RecepcionEquipo.IdClienteNavigation.Correo</p>
    <p>Direccion: @Model.RecepcionEquipo.IdClienteNavigation.Direccion</p>
    <p>Observaciones: @Model.PobservacionesRecomendaciones</p>
    <p>
        Tipo: @{
            string tipoEquipo = "";
            switch (Model.RecepcionEquipo.TipoPc)
            {
                case 0:
                    tipoEquipo = "PC Torre";
                    break;
                case 1:
                    tipoEquipo = "Notebook";
                    break;
                case 2:
                    tipoEquipo = "All-In-One";
                    break;
                default:
                    tipoEquipo = "Desconocido";
                    break;
            }
            @tipoEquipo
        }
    </p>
    <p>Accesorios: @Model.RecepcionEquipo.Accesorio</p>
    <p>Marca: @Model.RecepcionEquipo.MarcaPc</p>
    <p>Modelo: @Model.RecepcionEquipo.ModeloPc</p>
    <p>S/N: @Model.RecepcionEquipo.Nserie</p>
    <p>
        Capacidad Ram: @{
            string memoriaRam = "";
            switch (Model.RecepcionEquipo.CapacidadRam)
            {
                case 0:
                    memoriaRam = "4 GB";
                    break;
                case 1:
                    memoriaRam = "6 GB";
                    break;
                case 2:
                    memoriaRam = "8 GB";
                    break;
                case 3:
                    memoriaRam = "16 GB";
                    break;
                case 4:
                    memoriaRam = "Otro";
                    break;
            }
            @memoriaRam
        }
    </p>
    <p>
        Almacenamiento: @{
            string almacenamiento = "";
            switch (Model.RecepcionEquipo.TipoAlmacenamiento)
            {
                case 0:
                    almacenamiento = "HDD";
                    break;
                case 1:
                    almacenamiento = "SDD Sata";
                    break;
                case 2:
                    almacenamiento = "SDD M.2";
                    break;
                case 3:
                    almacenamiento = "SSD NVM M.2";
                    break;
            }
            @almacenamiento
        }
    </p>
    <p>Capacidad Almacenamiento: @Model.RecepcionEquipo.CapacidadAlmacenamiento</p>
    <p>
        GPU: @{
            string gpu = "";
            switch (Model.RecepcionEquipo.TipoGpu)
            {
                case 0:
                    gpu = "Chip Integrado";
                    break;
                case 1:
                    gpu = "Tarjeta";
                    break;
                case 2:
                    gpu = "Otro";
                    break;
            }
            @gpu
        }
    </p>
    <p>Grafico: @Model.RecepcionEquipo.Grafico</p>
    <p>
        SO Instalado: @{
            string soinstalado = "";
            switch (Model.Soinstalado)
            {
                case 0:
                    soinstalado = "Windows 10";
                    break;
                case 1:
                    soinstalado = "Windows 11";
                    break;
                case 2:
                    soinstalado = "Linux";
                    break;
            }
            @soinstalado
        }
    </p>
    <p>
        Suite Office Instalado: @{
            string suiteofficeinstalada = "";
            switch (Model.Soinstalado)
            {
                case 0:
                    suiteofficeinstalada = "Microsoft Office 2013";
                    break;
                case 1:
                    suiteofficeinstalada = "Microsoft Office 2019";
                    break;
                case 2:
                    suiteofficeinstalada = "Microsoft Office 365";
                    break;
                case 3:
                    suiteofficeinstalada = "OpenOffice";
                    break;
            }
            @suiteofficeinstalada
        }
    </p>
    <p>
        Lector PDF Instalado: @{
            string lectorpdfinstalado = "";
            switch (Model.Soinstalado)
            {
                case 0:
                    lectorpdfinstalado = "No Instalado";
                    break;
                case 1:
                    lectorpdfinstalado = "Instalado";
                    break;
                case 2:
                    lectorpdfinstalado = "No Aplica";
                    break;
            }
            @lectorpdfinstalado
        }
    </p>
    <p>
        Navegador Web Instalado: @{
            string navegadorwebinstalado = "";
            switch (Model.NavegadorWebInstalado)
            {
                case 0:
                    navegadorwebinstalado = "No Instalado";
                    break;
                case 1:
                    navegadorwebinstalado = "Chrome";
                    break;
                case 2:
                    navegadorwebinstalado = "Chrome y Firefox";
                    break;
            }
            @navegadorwebinstalado
        }
    </p>
    <p>Antivirus Instalado: @Model.AntivirusInstalado</p>
</div>

<h2>Diagnóstico y Soluciones</h2>
<table class="table">
    <thead>
        <tr>
            <th>Descripcion Diagnostico</th>
            <th>Descripcion Solucion</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var diagnostico in Model.Diagnosticosolucions)
        {
            <tr>
                <td>@diagnostico.DescripcionDiagnostico</td>
                <td>@diagnostico.DescripcionSolucion</td>
                <td>
                    <a asp-action="Edit" asp-controller="Diagnosticosolucions" asp-route-id="@diagnostico.IdDiagnosticoSolucion"><button class="btn-primary">Editar</button></a> |
                    <a asp-action="Details" asp-controller="Diagnosticosolucions" asp-route-id="@diagnostico.IdDiagnosticoSolucion"><button class="btn-info">Detalles</button></a> |
                    <a asp-action="Delete" asp-controller="Diagnosticosolucions" asp-route-id="@diagnostico.IdDiagnosticoSolucion"><button class="btn-danger">Borrar</button></a>
                </td>
            </tr>
        }
    </tbody>
</table>